export const sample_foods = [
 
    {
      id: '1',
      name: 'Pizza Pepperoni',
      cookTime: '10-20',
      price: 250,
      favorite: false,
      origins: ['italy'],
      stars: 4.5,
      imageUrl: 'food-1.jpg',
      tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
      id: '2',
      name: 'Meatball',
      price: 350,
      cookTime: '20-30',
      favorite: true,
      origins: ['persia', 'middle east', 'china'],
      stars: 5,
      imageUrl: 'food-2.jpg',
      tags: ['SlowFood', 'Lunch'],
    },
    {
      id: '3',
      name: 'Hamburger',
      price: 220,
      cookTime: '10-15',
      favorite: false,
      origins: ['germany', 'us'],
      stars: 3.5,
      imageUrl: 'food-3.jpg',
      tags: ['FastFood', 'Hamburger'],
    },
    {
      id: '4',
      name: 'Fried Potatoes',
      price: 75,
      cookTime: '15-20',
      favorite: true,
      origins: ['belgium', 'france'],
      stars: 3,
      imageUrl: 'food-4.jpg',
      tags: ['FastFood', 'Fry','Snacks'],
    },
    {
      id: '5',
      name: 'Chicken Soup',
      price: 150,
      cookTime: '40-50',
      favorite: false,
      origins: ['india', 'asia'],
      stars: 3.5,
      imageUrl: 'food-5.jpg',
      tags: ['SlowFood', 'Soup'],
    },
    {
      id: '6',
      name: 'Vegetables Pizza',
      price: 200,
      cookTime: '40-50',
      favorite: false,
      origins: ['italy'],
      stars: 4.0,
      imageUrl: 'food-6.jpg',
      tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
      id: '7',
      name: 'Hyderabad Biryani',
      price: 350,
      cookTime: '50-60',
      favorite: false,
      origins: ['india'],
      stars: 5.0,
      imageUrl: 'food-7.jpg',
      tags: ['Spice', 'South Asia', 'Lunch'],
    },
    {
      id: '8',
     name: 'Donuts',
     price: 50,
     cookTime: '10-15',
     favorite: false,
     origins: ['Dutch'],
     stars: 4.0,
     imageUrl: 'food-8.jpg',
     tags: [ 'Pastry', 'Snacks'],
   },
    

      ];
  
  export const sample_tags = [
    { name: 'All', count: 8 },
    { name: 'FastFood', count: 4 },
    { name: 'Pizza', count: 2 },
    { name: 'Lunch', count: 4 },
    { name: 'SlowFood', count: 2 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fry', count: 1 },
    { name: 'Soup', count: 1 },
    { name: 'Spice', count: 1 },
    { name: 'Pastry', count: 1 },
    { name: 'Snacks', count: 2},
    
  ];
  
  export const sample_users = [
    {
      id: 1,
      name: 'John Doe',
      email: 'john@gmail.com',
      password: '12345',
      address: 'Toronto On',
      isAdmin: true,
    },
    {
      id: 2,
      name: 'Jane Doe',
      email: 'jane@gmail.com',
      password: '12345',
      address: 'Shanghai',
      isAdmin: true,
    },
  ];
  